name: "w.m"
picture: "assets/img/picture.jpg"
bio: "The one who is good and shit at UT/DT and MK💜 Also I make music I think….."
meta:
  lang: "en"
  description: "The one who is good and shit at UT/DT and MK💜 Also I make music I think….."
  title: "@waterdmoon"
  author: "waterdmoon"
  siteUrl: "https://wmrom.github.io"
links:
  - name: "Youtube"
    url: "https://youtube.com/@waterdmoon"
  - name: "Second"
    url: "https://www.youtube.com/@ju5tnox"
  - name: "BlueSky"
    url: "bsky.app/profile/waterdmoon.bsky.social"
  - name: "Speedrun page"
    url: "https://www.speedrun.com/users/waterdmoon"
  - name: "Github"
    url: "https://github.com/wmrom"
  # - name: ""
  #   url: ""
theme: "custom"
